version: '3'
services:
  superveda-jsp:
    build:
      context: ./tomcat
    ports:
      - "8080:8080"
    links:
      - superveda-db
    environment:
      DB_HOSTNAME: superveda-db
  superveda-db:
    build:
      context: ./mysql
    ports:
      - "3306:3306"
